[package]
name = "hashmap_commands"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rus_key_lib = { path = "../../lib" }
# command crate
expired_commands = { path = "../expired_commands" }
